### ISSUE TITLE
Page 17 of ConfigGuide.pdf is no longer accurate To ensure ‘Developer Mode’ is on:

### ISSUE THREAD

**Issue by wptracy** [toddaustin07/rpi-st-device#10]
To ensure ‘Developer Mode’ is on:

On the main screen of the mobile app, tap the menu icon in the upper left, then the gray gear icon
in the upper right. Scroll all the way down in the options and make sure the Developer Mode
switch is enabled. If it's not, enable it, back out, close the app, and restart the app.

https://developer.smartthings.com/docs/devices/test-your-device/#enable-developer-mode-in-the-smartthings-app

Enable Developer Mode in the SmartThings App[#](https://developer.smartthings.com/docs/devices/test-your-device/#enable-developer-mode-in-the-smartthings-app)

You must enable developer mode before you can test using the SmartThings app.

    Launch the SmartThings app.
    Tap the Menu tab on the bottom navigation bar.
    Tap the Settings gear icon. The SmartThings settings menu will appear.
    Long-press About SmartThings for 5 seconds. A developer mode toggle will appear in the settings menu.
    Enable Developer Mode.
    Restart the SmartThings app.

**Comment by toddaustin07** [comment]
Much appreciated.  There's been a couple changes in the way things work in the app that requires some updates to the docs.

**Comment by toddaustin07** [comment]
Done

**Comment by toddaustin07** [comment]
Done
