### ISSUE TITLE
Provisioning Failure

### ISSUE THREAD

**Issue by Delgreco007** [toddaustin07/rpi-st-device#2]
I cannot get all the way through device provisioning. On the app, I get to 38-39% complete. This is right after I select the SSID to tell my device what to connect to when provisioning is done. The provisioning then times out. This is on 64 bit.  The 32 bit system made it all the way to the end yesterday, although I think I had to run it twice.

**Comment by Delgreco007** [comment]
This one I was able to solve with STProv64. It indicated that the SSID was not found. For whatever reason, this particular Pi (don't know whether it's a general Pi4 issue or not), will often show a good wifi connection but then will only have intermittent connectivity. I moved the Pi physically closer to my AP, and the provisioning went through without a hassle.

**Comment by toddaustin07** [comment]
So total success?  You got the example app operational?  That would be good news.

FYI, I tried out the python  option under 64 bit and has a problem compiling the CFFI wrapper, so I'll have to investigate that.

**Comment by Delgreco007** [comment]
Yes, fully operational. No problems.
