### ISSUE TITLE
Config Guide Links Incorrect

### ISSUE THREAD

**Issue by EricKit** [toddaustin07/rpi-st-device#4]
For the file `/ConfigGuide.pdf`:

The link near the bottom of page 1 labeled `my github repository` references `https://github.com/todd_austin/rpi-st-device.git` resulting in a 404. Perhaps replace with `https://github.com/toddaustin07/rpi-st-device`.

The link at the bottom of page 1 to the `“Direct-connected devices”` references `https://smartthings.developer.samsung.com/docs/devices/direct-connected-devices/overview.html` which goes to a "We've Moved" page. Perhaps change the link to `https://developer-preview.smartthings.com/docs/devices/direct-connected/get-started`, which I'm guessing will change again in the near future.

**Comment by toddaustin07** [comment]
Thank you for your feedback on the config guide!  I'll take a look at these and get them fixed.
