### ISSUE TITLE
Revision c03114 not tested or supported

### ISSUE THREAD

**Issue by joecoolish** [toddaustin07/rpi-st-device#5]
I just got a new pi4 and the version is c03114.  I'm going to modify the `mastersetup` to add this version and see if it works!

**Comment by toddaustin07** [comment]
Go for it!  Let me know how you make out.

**Comment by toddaustin07** [comment]
Hi - Did you ever have success with your new Pi4?  If so, I'd like to add it to mastersetup.

**Comment by joecoolish** [comment]
Sorry for the delay @toddaustin07,  I finally had some time and got it loaded.  I was successful with c03114.  Please add it to the list!

**Comment by toddaustin07** [comment]
Thank you for letting me know.
