### ISSUE TITLE
Getting argument values in Python

### ISSUE THREAD

**Issue by joecoolish** [toddaustin07/rpi-st-device#8]
Hi @toddaustin07, thank you again for all the hard work! 

I'm building out a python app and I have some contributions to give back (specifically in the STDevice.py file), but I'm struggling to get the argument values passed by ST into my python app.  I have an event handler `handleSetVolume ` that gets call correctly, and I can see in the log files that the value is being passed appropriately:

```
I (1671748539:889) [IoT]: iot_cap_sub_cb(844) > command : {"commands":[{"id":"e3a0bd5e-ff3b-4911-9149-166f82945233","component":"main","capability":"audioVolume","command":"setVolume","arguments":[52]}]}
```

But I can't for the life of me find where that argument is located.  I'm assuming that it's part of the `userdata.cmd_data`, but I can't figure out how to make that value something that python recognizes.  Here is my event handler code so far:

```

@ffi.def_extern()
def handleSetVolume(handle, userdata, value):

    print ("\n\033[96mVolume Set invoked: ", userdata.cmd_data)

    global cur_vol
    cur_vol = userdata.cmd_data

    seqnum = STDevice.setstrattr(handle, "volume", userdata.cmd_data)

    if seqnum > 0:
        print("\033[96mVolume attribute set to ", userdata.cmd_data, "; sequence number =", seqnum, "\033[0m\n")
    else:
        print("\033[91mError updating volume attribute\033[0m\n")

```

The log message that is printed is:

```
Volume Set invoked:  <cdata 'iot_cap_val_t[5]' 0xb620cc60>
```

How do I convert from `iot_cap_val_t[5]` to get the value of the argument?

**Comment by joecoolish** [comment]
I figured it out:

```
    # Data is a string
    data = userdata.cmd_data[0].string
    data = ffi.string(data).decode()

    # Data is a number
    data = userdata.cmd_data[0].number
```

**Comment by toddaustin07** [comment]
Hey I'm glad you got it working.  Sorry I hadn't time to look at it yet myself.

Let me know if there's some code you'd like to contribute to the Python part of the package.
