### ISSUE TITLE
ConfigGuide.pdf page 10 cd command needs ~/rpi-st-device

### ISSUE THREAD

**Issue by wptracy** [toddaustin07/rpi-st-device#9]
You can run the setup script now:
cd /rpi-st-device
sudo ./SoftAPconfig

Should be:
You can run the setup script now:
cd ~/rpi-st-device
sudo ./SoftAPconfig

**Comment by toddaustin07** [comment]
Thanks for catching that!  I will fix it.

**Comment by toddaustin07** [comment]
Done
